name: Deploy to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to SiteGround
      env:
        SITEGROUND_SSH_KEY: ${{ secrets.SITEGROUND_SSH_KEY }}
        SITEGROUND_USER: u1996-mgm3tmy4drfs
        SITEGROUND_HOST: gcam1014.siteground.biz
      run: |
        mkdir -p ~/.ssh
        echo "$SITEGROUND_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no $SITEGROUND_USER@$SITEGROUND_HOST -p 18765 "cd /www/johnkyle.dev/public_html && git pull origin main"
